import type { Metadata, Viewport } from "next";
import "./globals.css";
import { supabaseServer } from "@/lib/supabase/server";
import GlobalOverlays from "@/components/GlobalOverlays";
import WhatsNewToast from "@/components/WhatsNewToast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await supabaseServer();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang="en">
      <body className="antialiased">
        {children}
        {user ? <GlobalOverlays ownerKey={user.id} /> : null}
        <WhatsNewToast />
      </body>
    </html>
  );
}
